
networks:
  invoicing-app-network:
    driver: bridge

volumes:
  invoicing-app-data:
    driver: local
  keycloak-data:
    driver: local

services:

#  postgres-invoicehub:
#    image: postgres
#    container_name: invoicing-postgres-db
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: faith
#      POSTGRES_DB: invoicing_db
#    networks:
#      - invoicing-app-network
#    volumes:
#      - invoicing-app-data:/var/lib/postgresql/data
#    ports:
#      - '5432:5432'
#    restart: always
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U postgres -d invoicing_db" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5

  postgres-keycloak:
    image: postgres
    container_name: keycloak-postgres-db
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak_db
    networks:
      - invoicing-app-network
    volumes:
      - keycloak-data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d keycloak_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  invoicing-app:
    image: fai7h01/invoicehub:v1
    container_name: invoicing
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/invoicing_db
      DB_USERNAME: postgres
      DB_PASSWORD: faith
    networks:
      - invoicing-app-network
    ports:
      - '9090:9090'
    depends_on:
      postgres-invoicehub:
        condition: service_healthy

  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    container_name: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres-keycloak
      DB_DATABASE: keycloak_db
      DB_USER: postgres
      DB_SCHEMA: public
      DB_PASSWORD: faith
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/realm-export.json
    ports:
      - '8080:8080'
    volumes:
      - ./keycloak-config:/opt/keycloak/data/import
      - keycloak-data:/opt/keycloak/data
    networks:
      - invoicing-app-network
    depends_on:
      postgres-keycloak:
        condition: service_healthy